#!/usr/bin/env node
/* Pre-render a realistic Go stone "click" and write js/sound-data.js as a
 * base64 WAV data-URI. This is a *physically-modelled* sample (a sharp noise
 * transient plus several inharmonic, exponentially-decaying wood resonances),
 * baked once offline so the app can play a real audio buffer instead of a live
 * oscillator graph. Re-run to regenerate: `node scripts/gen-click.js`.
 *
 * To use a genuine field recording instead, just replace the `click` data-URI
 * in js/sound-data.js with your own WAV/MP3 data-URI.
 */
"use strict";
const fs = require("fs");
const path = require("path");

const SR = 44100;
const DUR = 0.16;                  // seconds
const N = Math.floor(SR * DUR);

// Inharmonic resonant modes of a stone striking a wooden board: [freqHz, decaySec, amp]
const MODES = [
  [180, 0.11, 0.55],   // low wood body "thunk"
  [520, 0.085, 0.5],
  [1150, 0.055, 0.42],
  [1950, 0.035, 0.3],
  [2750, 0.025, 0.2]
];

function render() {
  const buf = new Float32Array(N);
  // 1) modal resonances
  for (let i = 0; i < N; i++) {
    const t = i / SR;
    let s = 0;
    for (const [f, dec, amp] of MODES) {
      s += amp * Math.sin(2 * Math.PI * f * t) * Math.exp(-t / dec);
    }
    buf[i] = s;
  }
  // 2) sharp broadband click transient (the stone "tick"), very fast decay
  for (let i = 0; i < N; i++) {
    const t = i / SR;
    const env = Math.exp(-t / 0.0025);
    if (env < 1e-4) break;
    buf[i] += (Math.random() * 2 - 1) * env * 0.7;
  }
  // 3) overall tiny attack smoothing (first ~0.5ms) to avoid a hard DC pop
  const atk = Math.floor(SR * 0.0005);
  for (let i = 0; i < atk; i++) buf[i] *= i / atk;

  // normalize to ~0.9 peak
  let peak = 0;
  for (let i = 0; i < N; i++) peak = Math.max(peak, Math.abs(buf[i]));
  const g = peak > 0 ? 0.9 / peak : 1;
  for (let i = 0; i < N; i++) buf[i] *= g;
  return buf;
}

function toWav(samples) {
  const bytesPerSample = 2, numChannels = 1;
  const dataLen = samples.length * bytesPerSample;
  const b = Buffer.alloc(44 + dataLen);
  b.write("RIFF", 0); b.writeUInt32LE(36 + dataLen, 4); b.write("WAVE", 8);
  b.write("fmt ", 12); b.writeUInt32LE(16, 16); b.writeUInt16LE(1, 20);
  b.writeUInt16LE(numChannels, 22); b.writeUInt32LE(SR, 24);
  b.writeUInt32LE(SR * numChannels * bytesPerSample, 28);
  b.writeUInt16LE(numChannels * bytesPerSample, 32); b.writeUInt16LE(16, 34);
  b.write("data", 36); b.writeUInt32LE(dataLen, 40);
  let o = 44;
  for (let i = 0; i < samples.length; i++) {
    let v = Math.max(-1, Math.min(1, samples[i]));
    b.writeInt16LE((v * 32767) | 0, o); o += 2;
  }
  return b;
}

const wav = toWav(render());
const b64 = wav.toString("base64");
const out =
  "/* AUTO-GENERATED by scripts/gen-click.js — a pre-rendered stone-click WAV\n" +
  " * (physical model: noise transient + inharmonic wood resonances), embedded\n" +
  " * as a base64 data-URI so the app stays self-contained. Replace `click` with\n" +
  " * your own recording's data-URI to use a real sample. */\n" +
  "(function (GT) {\n  GT.soundData = {\n    click: \"data:audio/wav;base64," + b64 + "\"\n  };\n})(window.GT = window.GT || {});\n";

const dest = path.join(__dirname, "..", "js", "sound-data.js");
fs.writeFileSync(dest, out);
console.log("Wrote " + dest + " (" + Math.round(wav.length / 1024) + " KB WAV, " + Math.round(b64.length / 1024) + " KB base64)");
